import { Platform, StyleSheet } from 'react-native';

export const DARK_MAP_STYLE = [
  { elementType: 'geometry', stylers: [{ color: '#1f2933' }] },
  { elementType: 'labels.icon', stylers: [{ visibility: 'off' }] },
  { elementType: 'labels.text.fill', stylers: [{ color: '#e0e6ed' }] },
  { elementType: 'labels.text.stroke', stylers: [{ color: '#1a202c' }] },
  {
    featureType: 'administrative',
    elementType: 'geometry',
    stylers: [{ color: '#1a202c' }],
  },
  {
    featureType: 'poi',
    elementType: 'geometry',
    stylers: [{ color: '#1f2933' }],
  },
  {
    featureType: 'poi',
    elementType: 'labels.text.fill',
    stylers: [{ color: '#cbd5f5' }],
  },
  {
    featureType: 'poi.park',
    elementType: 'geometry',
    stylers: [{ color: '#1b2a33' }],
  },
  {
    featureType: 'poi.park',
    elementType: 'labels.text.fill',
    stylers: [{ color: '#99f6e4' }],
  },
  {
    featureType: 'road',
    elementType: 'geometry',
    stylers: [{ color: '#2a3642' }],
  },
  {
    featureType: 'road',
    elementType: 'geometry.stroke',
    stylers: [{ color: '#101820' }],
  },
  {
    featureType: 'road',
    elementType: 'labels.text.fill',
    stylers: [{ color: '#d1d9e6' }],
  },
  {
    featureType: 'road.highway',
    elementType: 'geometry',
    stylers: [{ color: '#3a4759' }],
  },
  {
    featureType: 'road.highway',
    elementType: 'geometry.stroke',
    stylers: [{ color: '#0f172a' }],
  },
  {
    featureType: 'road.highway',
    elementType: 'labels.text.fill',
    stylers: [{ color: '#f8fafc' }],
  },
  {
    featureType: 'transit',
    elementType: 'geometry',
    stylers: [{ color: '#1a2430' }],
  },
  {
    featureType: 'water',
    elementType: 'geometry',
    stylers: [{ color: '#0f172a' }],
  },
  {
    featureType: 'water',
    elementType: 'labels.text.fill',
    stylers: [{ color: '#94a3b8' }],
  },
];

export const BRAND = {
  primary: '#FF4D00',
  bg: '#FFF5ED',
  surface: '#FFFFFF',
  line: '#FFE8D2',
  ink: '#3C1E12',
  inkMuted: '#6B4A3F',
  metaBg: '#FFE8D2',
  accentSoft: '#FFD8BF',
  blue: '#2563EB',
  overlay: 'rgba(60,30,18,0.35)',
};

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: BRAND.bg },
  map: { ...StyleSheet.absoluteFillObject },
  navigationStopWrap: { position: 'absolute', right: 20 },
  navigationStopButton: {
    backgroundColor: BRAND.surface,
    borderColor: BRAND.line,
    borderWidth: 1,
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: BRAND.ink,
    shadowOpacity: 0.08,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 6,
  },
  userMarkerHalo: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(37,99,235,0.18)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: BRAND.blue,
    shadowColor: BRAND.blue,
    shadowOpacity: 0.4,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 10,
  },
  userMarker: {
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: BRAND.surface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  turnPin: {
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderRadius: 12,
    backgroundColor: BRAND.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  banner: {
    position: 'absolute',
    top: Platform.OS === 'ios' ? 60 : 40,
    left: 20,
    right: 20,
    backgroundColor: BRAND.ink,
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    padding: 12,
  },
  bannerIcon: { marginRight: 12 },
  instruction: { color: BRAND.surface, fontSize: 16, fontWeight: '600' },
  sub: { color: 'rgba(255,255,255,0.85)', fontSize: 13 },
  thenChip: {
    marginTop: 10,
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: BRAND.accentSoft,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: BRAND.line,
  },
  thenText: { color: BRAND.ink, fontSize: 12, fontWeight: '600', marginRight: 6 },
  etaBar: {
    backgroundColor: BRAND.metaBg,
    borderRadius: 16,
    paddingHorizontal: 18,
    paddingVertical: 14,
    marginHorizontal: 20,
    marginTop: 8,
    borderWidth: 1,
    borderColor: BRAND.line,
    shadowColor: BRAND.ink,
    shadowOpacity: 0.05,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 3 },
    elevation: 3,
  },
  etaPrimary: { color: BRAND.ink, fontSize: 18, fontWeight: '700' },
  etaSecondary: { color: BRAND.inkMuted, marginTop: 4, fontSize: 14 },
  mapControls: { position: 'absolute', right: 20, alignItems: 'flex-end' },
  mapButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: BRAND.surface,
    borderColor: BRAND.line,
    borderWidth: 1,
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 10,
    shadowColor: BRAND.ink,
    shadowOpacity: 0.08,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 4,
  },
  mapButtonText: { marginLeft: 6, color: BRAND.ink, fontWeight: '600' },
  sheetBase: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    backgroundColor: BRAND.surface,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    paddingHorizontal: 20,
    paddingTop: 8,
    borderColor: BRAND.line,
    borderWidth: 1,
    shadowColor: BRAND.ink,
    shadowOpacity: 0.05,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: -2 },
    elevation: 6,
  },
  handle: { alignItems: 'center', paddingTop: 12, paddingBottom: 6 },
  grabber: {
    width: 48,
    height: 5,
    borderRadius: 3,
    backgroundColor: BRAND.line,
  },
  sheetContent: { paddingBottom: 60 },
  sheetContentWithSummary: { paddingTop: 12 },
  headerCard: {
    backgroundColor: BRAND.surface,
    borderRadius: 20,
    padding: 18,
    marginBottom: 18,
    borderColor: BRAND.line,
    borderWidth: 1,
    shadowColor: BRAND.ink,
    shadowOpacity: 0.03,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  iconFab: {
    position: 'absolute',
    top: 18,
    right: 18,
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: BRAND.primary,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 10,
    elevation: 3,
  },
  name: { fontSize: 22, fontWeight: '800', color: BRAND.ink },
  meta: { color: BRAND.inkMuted, marginTop: 4 },
  badgeRow: { flexDirection: 'row', flexWrap: 'wrap', marginTop: 12 },
  actionsRow: { flexDirection: 'row', gap: 12, marginTop: 16 },
  actionBtn: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  actionText: { color: BRAND.surface, fontWeight: '700' },
  previewRouteSummary: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 16,
    backgroundColor: BRAND.metaBg,
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: BRAND.line,
  },
  previewRouteIcon: { marginRight: 10 },
  previewRouteText: { color: BRAND.ink, fontWeight: '600' },
  section: { marginBottom: 16 },
  sectionTitle: { fontWeight: 'bold', marginBottom: 8, color: BRAND.ink },
  body: { color: BRAND.inkMuted, lineHeight: 20 },
  nextStepCard: {
    marginTop: 16,
    borderRadius: 16,
    padding: 16,
    backgroundColor: BRAND.surface,
    borderWidth: 1,
    borderColor: BRAND.line,
  },
  nextStepTitle: { fontWeight: '700', fontSize: 16, color: BRAND.ink, marginBottom: 6 },
  nextStepInstruction: { color: BRAND.ink, lineHeight: 20 },
  nextStepMeta: { flexDirection: 'row', flexWrap: 'wrap', marginTop: 10 },
  chipWrap: { flexDirection: 'row', flexWrap: 'wrap' },
  itemCard: {
    padding: 16,
    borderRadius: 18,
    backgroundColor: BRAND.surface,
    borderColor: BRAND.line,
    borderWidth: 1,
    shadowColor: BRAND.ink,
    shadowOpacity: 0.02,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
    elevation: 1,
    marginRight: 14,
    width: 200,
  },
  itemName: { fontWeight: '700', fontSize: 16, color: BRAND.ink },
  reviewCard: {
    backgroundColor: BRAND.surface,
    borderColor: BRAND.line,
    borderWidth: 1,
    borderRadius: 20,
    padding: 16,
    shadowColor: BRAND.ink,
    shadowOpacity: 0.02,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
    elevation: 1,
    marginBottom: 10,
  },
  reviewAuthor: { fontWeight: '700', color: BRAND.ink },
  reviewMeta: { color: BRAND.inkMuted, marginTop: 4 },
  reviewBody: { marginTop: 8, color: BRAND.ink },
  overlay: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 24,
    zIndex: 9999,
    elevation: 9999,
  },
  overlayBg: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: BRAND.overlay,
    zIndex: 9998,
    elevation: 9998,
  },
  modalCard: {
    width: '100%',
    maxWidth: 360,
    backgroundColor: BRAND.surface,
    borderRadius: 20,
    padding: 18,
    borderWidth: 1,
    borderColor: BRAND.line,
    shadowColor: BRAND.ink,
    shadowOpacity: 0.05,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 10000,
    zIndex: 10000,
  },
  modalTitle: {
    fontWeight: '800',
    fontSize: 16,
    marginBottom: 8,
    color: BRAND.ink,
  },
  modalHelper: { color: BRAND.inkMuted, textAlign: 'center' },
  modalLabel: {
    marginTop: 14,
    marginBottom: 8,
    fontWeight: '600',
    color: BRAND.ink,
  },
  input: {
    borderWidth: 1,
    borderColor: BRAND.line,
    borderRadius: 12,
    padding: 12,
    minHeight: 72,
    textAlignVertical: 'top',
    backgroundColor: BRAND.surface,
    color: BRAND.ink,
  },
  submitBtn: {
    marginTop: 14,
    paddingVertical: 12,
    borderRadius: 12,
    alignItems: 'center',
  },
  submitText: { color: BRAND.surface, fontWeight: '700' },
  modalSuccess: { alignItems: 'center' },
  badge: {
    backgroundColor: BRAND.metaBg,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 14,
    marginRight: 8,
    marginBottom: 8,
  },
  badgeText: { fontSize: 12, color: BRAND.ink, fontWeight: '600' },
  chip: {
    backgroundColor: BRAND.metaBg,
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 18,
    marginRight: 8,
    marginBottom: 8,
  },
  chipText: { color: BRAND.ink, fontWeight: '600' },
  starRow: { flexDirection: 'row', alignItems: 'center' },
  star: { fontSize: 20, color: BRAND.primary },
  starMuted: { fontSize: 20, color: BRAND.line },
  starCount: { marginLeft: 8, color: BRAND.inkMuted },
});
